//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftStore.IsoTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftStore.IsoTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BeginBurningButton {
            get {
                object obj = ResourceManager.GetObject("BeginBurningButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BeginCopyingButton {
            get {
                object obj = ResourceManager.GetObject("BeginCopyingButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BrowseButton {
            get {
                object obj = ResourceManager.GetObject("BrowseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CancelButton {
            get {
                object obj = ResourceManager.GetObject("CancelButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ChangeUsbButton {
            get {
                object obj = ResourceManager.GetObject("ChangeUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Backup 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelCaption {
            get {
                return ResourceManager.GetString("ConfirmCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You currently have a backup in progress.  Canceling the backup will leave your media in an invalid state.  Are you sure you wish to cancel? 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelMessage {
            get {
                return ResourceManager.GetString("ConfirmCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CopyButton {
            get {
                object obj = ResourceManager.GetObject("CopyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Removable Disk 的本地化字符串。
        /// </summary>
        internal static string DefaultDriveLabel {
            get {
                return ResourceManager.GetString("DefaultDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (estimated time remaining {1}) 的本地化字符串。
        /// </summary>
        internal static string DvdBurningProgress {
            get {
                return ResourceManager.GetString("DvdBurningProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DvdButton {
            get {
                object obj = ResourceManager.GetObject("DvdButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 The disc does not have sufficient free space.  Please insert a blank DVD and try again. 的本地化字符串。
        /// </summary>
        internal static string DvdFreeSpaceMessage {
            get {
                return ResourceManager.GetString("DvdFreeSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DvdImage {
            get {
                object obj = ResourceManager.GetObject("DvdImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to locate a compatible DVD drive.  Please make sure your DVD drive is connected and capable of creating discs. 的本地化字符串。
        /// </summary>
        internal static string DvdNoDrivesMessage {
            get {
                return ResourceManager.GetString("DvdNoDrivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no disc in the drive.  Please insert a blank disc and try again. 的本地化字符串。
        /// </summary>
        internal static string DvdNoMediaMessage {
            get {
                return ResourceManager.GetString("DvdNoMediaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The disc is not blank.  Please insert a blank DVD and try again. 的本地化字符串。
        /// </summary>
        internal static string DvdNotBlankMessage {
            get {
                return ResourceManager.GetString("DvdNotBlankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DVD drive is still trying to read the disc.  Please wait a few moments and try again. 的本地化字符串。
        /// </summary>
        internal static string DvdNotReadyMessage {
            get {
                return ResourceManager.GetString("DvdNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready to burn. Click &quot;Begin burning&quot; to create the backup DVD. 的本地化字符串。
        /// </summary>
        internal static string DvdReadyMessage {
            get {
                return ResourceManager.GetString("DvdReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EraseUsbButton {
            get {
                object obj = ResourceManager.GetObject("EraseUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 http://go.microsoft.com/fwlink/?LinkId=163455&amp;clcid=0x409 的本地化字符串。
        /// </summary>
        internal static string HelpLinkUrl {
            get {
                return ResourceManager.GetString("HelpLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid ISO File 的本地化字符串。
        /// </summary>
        internal static string IsoInvalidCaption {
            get {
                return ResourceManager.GetString("IsoInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected file is not a valid ISO file.  Please select a valid ISO file and try again. 的本地化字符串。
        /// </summary>
        internal static string IsoInvalidMessage {
            get {
                return ResourceManager.GetString("IsoInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO File Not Selected 的本地化字符串。
        /// </summary>
        internal static string IsoNotSelectedCaption {
            get {
                return ResourceManager.GetString("IsoNotSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select an ISO file. 的本地化字符串。
        /// </summary>
        internal static string IsoNotSelectedMessage {
            get {
                return ResourceManager.GetString("IsoNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MasterSprite {
            get {
                object obj = ResourceManager.GetObject("MasterSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NextButton {
            get {
                object obj = ResourceManager.GetObject("NextButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OpenDvdButton {
            get {
                object obj = ResourceManager.GetObject("OpenDvdButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OpenUsbButton {
            get {
                object obj = ResourceManager.GetObject("OpenUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RefreshButton {
            get {
                object obj = ResourceManager.GetObject("RefreshButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 This application requires Administrator privileges.  Please restart the tool as an Administrator. 的本地化字符串。
        /// </summary>
        internal static string RequireAdmin {
            get {
                return ResourceManager.GetString("RequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StartOverButton {
            get {
                object obj = ResourceManager.GetObject("StartOverButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Files copied successfully.  However, we were unable to run bootsect to make the USB device bootable.  If you need assistance with bootsect, please click the &quot;Online Help&quot; link above for more information. 的本地化字符串。
        /// </summary>
        internal static string StatusBootloaderError {
            get {
                return ResourceManager.GetString("StatusBootloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Burning disc... 的本地化字符串。
        /// </summary>
        internal static string StatusBurning {
            get {
                return ResourceManager.GetString("StatusBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup canceled.  Click “Start over” to try again. 的本地化字符串。
        /// </summary>
        internal static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling... 的本地化字符串。
        /// </summary>
        internal static string StatusCanceling {
            get {
                return ResourceManager.GetString("StatusCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup completed. 的本地化字符串。
        /// </summary>
        internal static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copying files... 的本地化字符串。
        /// </summary>
        internal static string StatusCopying {
            get {
                return ResourceManager.GetString("StatusCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The burning process failed.  Please check your DVD drive and the selected ISO file and try again. 的本地化字符串。
        /// </summary>
        internal static string StatusDvdError {
            get {
                return ResourceManager.GetString("StatusDvdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatting... 的本地化字符串。
        /// </summary>
        internal static string StatusFormatting {
            get {
                return ResourceManager.GetString("StatusFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 We were unable to copy your files.  Please check your USB device and the selected ISO file and try again. 的本地化字符串。
        /// </summary>
        internal static string StatusUsbError {
            get {
                return ResourceManager.GetString("StatusUsbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TermsOfUse.rtf 的本地化字符串。
        /// </summary>
        internal static string TermsOfUseFileName {
            get {
                return ResourceManager.GetString("TermsOfUseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 3 of 4: Insert blank DVD 的本地化字符串。
        /// </summary>
        internal static string TitleDvd {
            get {
                return ResourceManager.GetString("TitleDvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 4 of 4: Creating bootable DVD 的本地化字符串。
        /// </summary>
        internal static string TitleDvdProgress {
            get {
                return ResourceManager.GetString("TitleDvdProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootable DVD created successfully 的本地化字符串。
        /// </summary>
        internal static string TitleDvdProgressComplete {
            get {
                return ResourceManager.GetString("TitleDvdProgressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 1 of 4: Choose ISO file 的本地化字符串。
        /// </summary>
        internal static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 2 of 4: Choose media type 的本地化字符串。
        /// </summary>
        internal static string TitleMediaType {
            get {
                return ResourceManager.GetString("TitleMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 3 of 4: Insert USB device 的本地化字符串。
        /// </summary>
        internal static string TitleUsb {
            get {
                return ResourceManager.GetString("TitleUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 4 of 4: Creating bootable USB device 的本地化字符串。
        /// </summary>
        internal static string TitleUsbProgress {
            get {
                return ResourceManager.GetString("TitleUsbProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bootable USB device created successfully 的本地化字符串。
        /// </summary>
        internal static string TitleUsbProgressComplete {
            get {
                return ResourceManager.GetString("TitleUsbProgressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft ISO Backup Tool 的本地化字符串。
        /// </summary>
        internal static string ToolTitle {
            get {
                return ResourceManager.GetString("ToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap TryAgainButton {
            get {
                object obj = ResourceManager.GetObject("TryAgainButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 An unexpected error occurred.  If the problem continues please contact support. 的本地化字符串。
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in Application 的本地化字符串。
        /// </summary>
        internal static string UnhandledExceptionCaption {
            get {
                return ResourceManager.GetString("UnhandledExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UsbButton {
            get {
                object obj = ResourceManager.GetObject("UsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 If your device is not displayed click &quot;Refresh.&quot; 的本地化字符串。
        /// </summary>
        internal static string UsbDefaultMessage {
            get {
                return ResourceManager.GetString("UsbDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device {0} could not be found.  Please verify the drive is properly connected and click “Refresh.” 的本地化字符串。
        /// </summary>
        internal static string UsbDeviceNotFoundMessage {
            get {
                return ResourceManager.GetString("UsbDeviceNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} Free 的本地化字符串。
        /// </summary>
        internal static string UsbDriveFormat {
            get {
                return ResourceManager.GetString("UsbDriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have selected to erase all of the contents from the selected USB device {0}.  All contents on this device will be lost.  Are you sure you want to do this? 的本地化字符串。
        /// </summary>
        internal static string UsbEraseConfirm {
            get {
                return ResourceManager.GetString("UsbEraseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device {0} must be erased in order to continue.  Do you want to erase all contents from this device? 的本地化字符串。
        /// </summary>
        internal static string UsbEraseMessage {
            get {
                return ResourceManager.GetString("UsbEraseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceCancel {
            get {
                return ResourceManager.GetString("UsbFreeSpaceCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Enough Free Space 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceCaption {
            get {
                return ResourceManager.GetString("UsbFreeSpaceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erase USB Device 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceErase {
            get {
                return ResourceManager.GetString("UsbFreeSpaceErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device {0} does not have enough free space.  To continue, the contents of the device must be erased.  Would you like to erase all contents from the selected device? 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceMessage {
            get {
                return ResourceManager.GetString("UsbFreeSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UsbImage {
            get {
                object obj = ResourceManager.GetObject("UsbImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device {0} is in use by another program.  Please close all applications and try again. 的本地化字符串。
        /// </summary>
        internal static string UsbInUseMessage {
            get {
                return ResourceManager.GetString("UsbInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device is not compatible with this tool.  Please select another USB device and try again. 的本地化字符串。
        /// </summary>
        internal static string UsbInvalidMessage {
            get {
                return ResourceManager.GetString("UsbInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No compatible USB devices detected 的本地化字符串。
        /// </summary>
        internal static string UsbNoDrivesDropDown {
            get {
                return ResourceManager.GetString("UsbNoDrivesDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No compatible removable USB devices were detected.  Please connect a USB device that is at least 4GB and click “Refresh.” 的本地化字符串。
        /// </summary>
        internal static string UsbNoDrivesMessage {
            get {
                return ResourceManager.GetString("UsbNoDrivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteCancel {
            get {
                return ResourceManager.GetString("UsbOverwriteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files Already Exist 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteCaption {
            get {
                return ResourceManager.GetString("UsbOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite Files 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteConfirm {
            get {
                return ResourceManager.GetString("UsbOverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files of the same name already exist on {0}.  Would you like to overwrite these files? 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteMessage {
            get {
                return ResourceManager.GetString("UsbOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected USB device {0} is not large enough.  Please select a USB device that is at least 4GB and try again. 的本地化字符串。
        /// </summary>
        internal static string UsbSizeMessage {
            get {
                return ResourceManager.GetString("UsbSizeMessage", resourceCulture);
            }
        }
    }
}
