//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftStore.IsoTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftStore.IsoTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BeginBurningButton {
            get {
                object obj = ResourceManager.GetObject("BeginBurningButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BeginCopyingButton {
            get {
                object obj = ResourceManager.GetObject("BeginCopyingButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BrowseButton {
            get {
                object obj = ResourceManager.GetObject("BrowseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CancelButton {
            get {
                object obj = ResourceManager.GetObject("CancelButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ChangeUsbButton {
            get {
                object obj = ResourceManager.GetObject("ChangeUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 取消备份 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelCaption {
            get {
                return ResourceManager.GetString("ConfirmCancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您有正在进行中的备份，取消备份将导致你的介质处于无效状态。您确定要取消吗？ 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelMessage {
            get {
                return ResourceManager.GetString("ConfirmCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap CopyButton {
            get {
                object obj = ResourceManager.GetObject("CopyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 可移动磁盘 的本地化字符串。
        /// </summary>
        internal static string DefaultDriveLabel {
            get {
                return ResourceManager.GetString("DefaultDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (估计剩余时间 {1}) 的本地化字符串。
        /// </summary>
        internal static string DvdBurningProgress {
            get {
                return ResourceManager.GetString("DvdBurningProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DvdButton {
            get {
                object obj = ResourceManager.GetObject("DvdButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘没有足够的空闲空间，请插入一张空白dvd后再试一次。 的本地化字符串。
        /// </summary>
        internal static string DvdFreeSpaceMessage {
            get {
                return ResourceManager.GetString("DvdFreeSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DvdImage {
            get {
                object obj = ResourceManager.GetObject("DvdImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到一个兼容的DVD驱动器。请确保能够连接到您的DVD驱动器并能够创建光盘。 的本地化字符串。
        /// </summary>
        internal static string DvdNoDrivesMessage {
            get {
                return ResourceManager.GetString("DvdNoDrivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在驱动器中没有磁盘。请插入一张空白盘，然后再试一次。 的本地化字符串。
        /// </summary>
        internal static string DvdNoMediaMessage {
            get {
                return ResourceManager.GetString("DvdNoMediaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光盘不是空白。请插入一张空白DVD，然后再试一次。 的本地化字符串。
        /// </summary>
        internal static string DvdNotBlankMessage {
            get {
                return ResourceManager.GetString("DvdNotBlankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个DVD驱动器仍然在读盘，请稍等片刻，然后再试一次。 的本地化字符串。
        /// </summary>
        internal static string DvdNotReadyMessage {
            get {
                return ResourceManager.GetString("DvdNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备刻录，点击“开始刻录”来创建DVD备份。 的本地化字符串。
        /// </summary>
        internal static string DvdReadyMessage {
            get {
                return ResourceManager.GetString("DvdReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap EraseUsbButton {
            get {
                object obj = ResourceManager.GetObject("EraseUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 http://go.microsoft.com/fwlink/?LinkId=163455&amp;clcid=0x409 的本地化字符串。
        /// </summary>
        internal static string HelpLinkUrl {
            get {
                return ResourceManager.GetString("HelpLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的ISO文件 的本地化字符串。
        /// </summary>
        internal static string IsoInvalidCaption {
            get {
                return ResourceManager.GetString("IsoInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选定的文件不是有效的ISO文件。请选择一个有效的ISO文件，然后再试一次。 的本地化字符串。
        /// </summary>
        internal static string IsoInvalidMessage {
            get {
                return ResourceManager.GetString("IsoInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择ISO文件 的本地化字符串。
        /// </summary>
        internal static string IsoNotSelectedCaption {
            get {
                return ResourceManager.GetString("IsoNotSelectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个ISO文件 的本地化字符串。
        /// </summary>
        internal static string IsoNotSelectedMessage {
            get {
                return ResourceManager.GetString("IsoNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MasterSprite {
            get {
                object obj = ResourceManager.GetObject("MasterSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NextButton {
            get {
                object obj = ResourceManager.GetObject("NextButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OpenDvdButton {
            get {
                object obj = ResourceManager.GetObject("OpenDvdButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap OpenUsbButton {
            get {
                object obj = ResourceManager.GetObject("OpenUsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap RefreshButton {
            get {
                object obj = ResourceManager.GetObject("RefreshButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 此应用程序需要管理员权限，请已管理员身份重新启动 的本地化字符串。
        /// </summary>
        internal static string RequireAdmin {
            get {
                return ResourceManager.GetString("RequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap StartOverButton {
            get {
                object obj = ResourceManager.GetObject("StartOverButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 文件已成功复制。然而，我们都无法运行 bootsect，使 USB 设备启动。如果您需要 bootsect 的帮助信息，请单击上面的详细信息的&quot;联机帮助&quot;链接。 的本地化字符串。
        /// </summary>
        internal static string StatusBootloaderError {
            get {
                return ResourceManager.GetString("StatusBootloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光盘刻录中... 的本地化字符串。
        /// </summary>
        internal static string StatusBurning {
            get {
                return ResourceManager.GetString("StatusBurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份已取消。单击&quot;重新开始&quot;，再试一次。 的本地化字符串。
        /// </summary>
        internal static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在取消... 的本地化字符串。
        /// </summary>
        internal static string StatusCanceling {
            get {
                return ResourceManager.GetString("StatusCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份完成 的本地化字符串。
        /// </summary>
        internal static string StatusComplete {
            get {
                return ResourceManager.GetString("StatusComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在复制文件... 的本地化字符串。
        /// </summary>
        internal static string StatusCopying {
            get {
                return ResourceManager.GetString("StatusCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刻录失败！请检查您的 DVD 驱动器和选定的 ISO 文件，然后再试一次。 的本地化字符串。
        /// </summary>
        internal static string StatusDvdError {
            get {
                return ResourceManager.GetString("StatusDvdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在格式化... 的本地化字符串。
        /// </summary>
        internal static string StatusFormatting {
            get {
                return ResourceManager.GetString("StatusFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我们是无法复制您的文件。请检查您的 USB 设备和所选的 ISO 文件，再试一次。 的本地化字符串。
        /// </summary>
        internal static string StatusUsbError {
            get {
                return ResourceManager.GetString("StatusUsbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TermsOfUse.rtf 的本地化字符串。
        /// </summary>
        internal static string TermsOfUseFileName {
            get {
                return ResourceManager.GetString("TermsOfUseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 3/4 步： 插入空白 DVD光盘 的本地化字符串。
        /// </summary>
        internal static string TitleDvd {
            get {
                return ResourceManager.GetString("TitleDvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 4/4 步： 创建可启动的 DVD 的本地化字符串。
        /// </summary>
        internal static string TitleDvdProgress {
            get {
                return ResourceManager.GetString("TitleDvdProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DVD启动盘创建成功 的本地化字符串。
        /// </summary>
        internal static string TitleDvdProgressComplete {
            get {
                return ResourceManager.GetString("TitleDvdProgressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 1/4 步： 选择 ISO 文件 的本地化字符串。
        /// </summary>
        internal static string TitleMain {
            get {
                return ResourceManager.GetString("TitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 2/4 步： 选择媒体类型 的本地化字符串。
        /// </summary>
        internal static string TitleMediaType {
            get {
                return ResourceManager.GetString("TitleMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 3/4 步： 插入 USB 设备 的本地化字符串。
        /// </summary>
        internal static string TitleUsb {
            get {
                return ResourceManager.GetString("TitleUsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 4/4 步： 创建可引导 USB 设备 的本地化字符串。
        /// </summary>
        internal static string TitleUsbProgress {
            get {
                return ResourceManager.GetString("TitleUsbProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USB启动盘创建成功 的本地化字符串。
        /// </summary>
        internal static string TitleUsbProgressComplete {
            get {
                return ResourceManager.GetString("TitleUsbProgressComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft ISO 备份工具 的本地化字符串。
        /// </summary>
        internal static string ToolTitle {
            get {
                return ResourceManager.GetString("ToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap TryAgainButton {
            get {
                object obj = ResourceManager.GetObject("TryAgainButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误。如果问题仍然存在请联系支持。 的本地化字符串。
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序中的错误 的本地化字符串。
        /// </summary>
        internal static string UnhandledExceptionCaption {
            get {
                return ResourceManager.GetString("UnhandledExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UsbButton {
            get {
                object obj = ResourceManager.GetObject("UsbButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 如果未显示您的设备，则请单击&quot;刷新&quot;。 的本地化字符串。
        /// </summary>
        internal static string UsbDefaultMessage {
            get {
                return ResourceManager.GetString("UsbDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到所选的 USB 设备 {0}。请验证该驱动器已正确连接，然后单击&quot;刷新&quot;。 的本地化字符串。
        /// </summary>
        internal static string UsbDeviceNotFoundMessage {
            get {
                return ResourceManager.GetString("UsbDeviceNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - {1} Free 的本地化字符串。
        /// </summary>
        internal static string UsbDriveFormat {
            get {
                return ResourceManager.GetString("UsbDriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已选择从 USB 设备 {0} 抹去所有的内容。在此设备上的所有内容将都会丢失。你确定要这样做吗？ 的本地化字符串。
        /// </summary>
        internal static string UsbEraseConfirm {
            get {
                return ResourceManager.GetString("UsbEraseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选的 USB 设备 {0} 必须格式化后才能继续使用。你想要删除此设备的所有内容吗？ 的本地化字符串。
        /// </summary>
        internal static string UsbEraseMessage {
            get {
                return ResourceManager.GetString("UsbEraseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceCancel {
            get {
                return ResourceManager.GetString("UsbFreeSpaceCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有足够的可用空间 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceCaption {
            get {
                return ResourceManager.GetString("UsbFreeSpaceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 USB 设备 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceErase {
            get {
                return ResourceManager.GetString("UsbFreeSpaceErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选的 USB 设备 {0} 没有足够的可用空间。若要继续，必须清除设备的内容。你想从所选的设备中抹去所有的内容吗？ 的本地化字符串。
        /// </summary>
        internal static string UsbFreeSpaceMessage {
            get {
                return ResourceManager.GetString("UsbFreeSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap UsbImage {
            get {
                object obj = ResourceManager.GetObject("UsbImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 选定的 USB 设备 {0} 正在由另一个程序使用。请关闭所有应用程序，然后重试 的本地化字符串。
        /// </summary>
        internal static string UsbInUseMessage {
            get {
                return ResourceManager.GetString("UsbInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选的 USB 设备不是与此工具兼容。请选择另一个 USB 设备，然后重试。 的本地化字符串。
        /// </summary>
        internal static string UsbInvalidMessage {
            get {
                return ResourceManager.GetString("UsbInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到不兼容的 USB 设备 的本地化字符串。
        /// </summary>
        internal static string UsbNoDrivesDropDown {
            get {
                return ResourceManager.GetString("UsbNoDrivesDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到不兼容的可移动 USB 设备。请插上至少 4 GB 的 USB 设备，然后单击&quot;刷新&quot;。 的本地化字符串。
        /// </summary>
        internal static string UsbNoDrivesMessage {
            get {
                return ResourceManager.GetString("UsbNoDrivesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteCancel {
            get {
                return ResourceManager.GetString("UsbOverwriteCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已经存在 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteCaption {
            get {
                return ResourceManager.GetString("UsbOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖文件 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteConfirm {
            get {
                return ResourceManager.GetString("UsbOverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 上已存在具有相同名称的文件。是否要覆盖这些文件？ 的本地化字符串。
        /// </summary>
        internal static string UsbOverwriteMessage {
            get {
                return ResourceManager.GetString("UsbOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选的 USB 设备 {0} 空间不足。请选择至少 4 GB 的 USB 设备，然后重试。 的本地化字符串。
        /// </summary>
        internal static string UsbSizeMessage {
            get {
                return ResourceManager.GetString("UsbSizeMessage", resourceCulture);
            }
        }
    }
}
